/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import modele.dao.ConnexionBDD;

/**
 *
 * @author Benjamin
 */
public class JDialogAjouter extends javax.swing.JDialog {

    /**
     * Creates new form JDialogAjouter
     * @param parent
     * @param modal
     */
    public JDialogAjouter(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Vide les champs de textes
        jTextFieldCodeAjouter.setText("");
        jTextFieldLibelleAjouter.setText("");
        jTextFieldNbPlacesAjouter.setText("");
        jTextFieldTarifAjouter.setText("");
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelCode = new javax.swing.JLabel();
        jLabelLibelle = new javax.swing.JLabel();
        jLabelNbPlaces = new javax.swing.JLabel();
        jLabelTarif = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabelTitrePrincipal = new javax.swing.JLabel();
        jLabelCodeAjout = new javax.swing.JLabel();
        jLabelLibelleAjout = new javax.swing.JLabel();
        jLabelNbPlacesAjout = new javax.swing.JLabel();
        jLabelTarifAjout = new javax.swing.JLabel();
        jTextFieldCodeAjouter = new javax.swing.JTextField();
        jTextFieldLibelleAjouter = new javax.swing.JTextField();
        jTextFieldNbPlacesAjouter = new javax.swing.JTextField();
        jTextFieldTarifAjouter = new javax.swing.JTextField();
        jButtonOk = new javax.swing.JButton();
        jButtonAnnuler = new javax.swing.JButton();

        jLabelCode.setText("Code : ");

        jLabelLibelle.setText("Libellé :");

        jLabelNbPlaces.setText("NbPlaces :");

        jLabelTarif.setText("Tarif :");

        jTextField2.setText("code de l'excursion");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelTitrePrincipal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelTitrePrincipal.setText("Informations de l'excursion");
        jLabelTitrePrincipal.setMinimumSize(new java.awt.Dimension(200, 30));
        jLabelTitrePrincipal.setPreferredSize(new java.awt.Dimension(200, 30));

        jLabelCodeAjout.setText("Code : ");

        jLabelLibelleAjout.setText("Libellé :");

        jLabelNbPlacesAjout.setText("NbPlaces :");

        jLabelTarifAjout.setText("Tarif :");

        jTextFieldCodeAjouter.setText("Code de l'excursion");
        jTextFieldCodeAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodeAjouterActionPerformed(evt);
            }
        });

        jTextFieldLibelleAjouter.setText("Description de l'excursion");

        jTextFieldNbPlacesAjouter.setText("Nombre de places");
        jTextFieldNbPlacesAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNbPlacesAjouterActionPerformed(evt);
            }
        });

        jTextFieldTarifAjouter.setText("Tarif de l'excursion");

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelCodeAjout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelLibelleAjout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelNbPlacesAjout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelTarifAjout, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldCodeAjouter)
                            .addComponent(jTextFieldLibelleAjouter)
                            .addComponent(jTextFieldNbPlacesAjouter)
                            .addComponent(jTextFieldTarifAjouter)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(121, Short.MAX_VALUE)
                        .addComponent(jLabelTitrePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitrePrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCodeAjout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCodeAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLibelleAjout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldLibelleAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNbPlacesAjout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNbPlacesAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTarifAjout)
                    .addComponent(jTextFieldTarifAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonOk)
                    .addComponent(jButtonAnnuler))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCodeAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodeAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCodeAjouterActionPerformed

    private void jTextFieldNbPlacesAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNbPlacesAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNbPlacesAjouterActionPerformed
    
 /** 
  * gére l'événement de clic sur le bouton "OK"
  * Cette méthode est appelée lorsque l'utilisateur clique sur le bouton "OK"
  * Elle récupère les valeurs des champs de texte, valide les entées, et les données dans la base de données si toutes les conditions sont remplies 
  * @param evt 
  */
    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // Déclaration de variables
        int nbPlacesInt;// Nombre de places, doit être un entier positif ou zéro
        double tarifDouble; // Tarif, doit être un nombre positif   

        // Récupère le contenu de chaque champs de texte
        String codeExcursion = jTextFieldCodeAjouter.getText(); 
        String libelleExcursion = jTextFieldLibelleAjouter.getText();
        String nbPlacesStr = jTextFieldNbPlacesAjouter.getText();
        String tarifStr = jTextFieldTarifAjouter.getText();

        // Vérifie si l'un des champs de texte est vide
        if (codeExcursion.isEmpty() || libelleExcursion.isEmpty() || nbPlacesStr.isEmpty() || tarifStr.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Tous les champs doivent être remplis.");
            return;// Sortie de la méthode si des champs sont vides
        }

        
        try {
            // Conversion des chaînes de caractères en types numériques
            nbPlacesInt = Integer.parseInt(nbPlacesStr);
            tarifDouble = Double.parseDouble(tarifStr);
            
            // Vérifie que le nombre de places et le tarif sont valides
            if (nbPlacesInt <= 0 || tarifDouble < 0) {
                JOptionPane.showMessageDialog(null, "Le nombre de places et le tarif doivent être positifs.");
                return;// Sortie de la méthode si les valeurs ne sont pas valides
            }
        } catch (NumberFormatException e) {
            // Gestion des exceptions pour les conversions de type
            JOptionPane.showMessageDialog(null, "Veuillez entrer des valeurs numériques valides.");
            return;// Sortie de la méthode en cas d'erreur de format
        }

        try {
            // Insertion des données dans la base de données
            insertIntoDatabase(codeExcursion, libelleExcursion, nbPlacesInt, tarifDouble);
            // Recharge la liste des excursions après l'ajout
            ((JFrameLesExcursions) getParent()).rechargerExcursions();
            this.dispose();// Ferme la fenêtre actuelle
        } catch (SQLException ex) {
            // Gestion des exceptions pour les erreurs d'insertion dans la base de données
            JOptionPane.showMessageDialog(null, "Erreur lors de l'ajout dans la base de données : " + ex.getMessage());
              // Pour voir l'erreur dans la console
        }
    }
    
    /**
     * 
     * 
     * @param codeExcursion
     * @param libelleExcursion
     * @param nbPlaces
     * @param tarif
     * @throws SQLException 
     */
    private static void insertIntoDatabase(String codeExcursion, String libelleExcursion,int  nbPlaces, double tarif) throws SQLException {
        // Préparation de la requête SQL
        String sql = "INSERT INTO Excursion (Code, Libelle, NbPlaces, Tarif) VALUES (?, ?, ?, ?)";

        // Connexion à la base de données
        Connection connection = ConnexionBDD.getConnexion(); 
        PreparedStatement pstmt = connection.prepareStatement(sql);

        // On remplace chaque point d'interrogation par les informations correspodantes
        pstmt.setString(1, codeExcursion);
        pstmt.setString(2, libelleExcursion);
        pstmt.setInt(3, nbPlaces);
        pstmt.setDouble(4, tarif);

        // Exécution de la requête
        pstmt.executeUpdate();
        JOptionPane.showMessageDialog(null, "Excursion ajoutée avec succès !");
    
        
       
    }//GEN-LAST:event_jButtonOkActionPerformed

    /**
     * Bouton qui ferme la fenêtre (JDialogAjouter)
     * 
     * @param evt 
     */
    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        // Ferme la fenêtre et ne conserve pas le contenu effectif
        this.dispose();
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    /**
     * Méthode principale
     * 
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogAjouter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogAjouter dialog = new JDialogAjouter(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabelCode;
    private javax.swing.JLabel jLabelCodeAjout;
    private javax.swing.JLabel jLabelLibelle;
    private javax.swing.JLabel jLabelLibelleAjout;
    private javax.swing.JLabel jLabelNbPlaces;
    private javax.swing.JLabel jLabelNbPlacesAjout;
    private javax.swing.JLabel jLabelTarif;
    private javax.swing.JLabel jLabelTarifAjout;
    private javax.swing.JLabel jLabelTitrePrincipal;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldCodeAjouter;
    private javax.swing.JTextField jTextFieldLibelleAjouter;
    private javax.swing.JTextField jTextFieldNbPlacesAjouter;
    private javax.swing.JTextField jTextFieldTarifAjouter;
    // End of variables declaration//GEN-END:variables
}
