/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modele.dao.ConnexionBDD;
import modele.metier.MiniExcursion;

/**
 *
 * @author dejes
 */
public class JDialogaAjouterEtape extends javax.swing.JDialog {

    private MiniExcursion excursionCourante;
    
    /**
     * Creates new form JDialogaAjouterEtape
     * @param parent
     * @param modal
     */
    public JDialogaAjouterEtape(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Initialisation à vide des champs de textes
        jTextFieldNumEtape.setText("");
        jTextFieldDescription.setText("");
        jTextFieldDureePrevue.setText("");
        
    }
    /**
     * Stocke l'excursion dans la variable d'instance
     * 
     * @param me Excursion actuelle
     */
     public void setExcursion(MiniExcursion me) {
        this.excursionCourante = me;
    }

    /**
     * Insère une étape dns l'excursion actuelle
     * 
     * @param codeExcursion Identifiant de l'excursion actuelle
     * @param NumEtape Numéro de l'étape
     * @param Description Description de l'étape
     * @param DureePrevue Durée en (min) pour l'étape
     * @throws SQLException 
     */
    private void insertEtapeIntoDatabase(String codeExcursion, int NumEtape, String Description, int DureePrevue) throws SQLException {
        // Préparation de la requête SQL
        String sql = "INSERT INTO etape (CodeExcursion, NumEtape, Description, DureePrevue) VALUES (?, ?, ?, ?)";

        // Connexion à la base de données
        Connection connection = ConnexionBDD.getConnexion(); 
        PreparedStatement pstmt = connection.prepareStatement(sql);

        // On remplace chaque point d'interrogation par les informations correspodantes
        pstmt.setString(1, codeExcursion);
        pstmt.setInt(2, NumEtape);
        pstmt.setString(3, Description);
        pstmt.setDouble(4, DureePrevue);

        // Exécution de la requête
        pstmt.executeUpdate();
        JOptionPane.showMessageDialog(null, "Excursion ajoutée avec succès !");
       
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumEtape = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelDureePrevue = new javax.swing.JLabel();
        jTextFieldNumEtape = new javax.swing.JTextField();
        jTextFieldDescription = new javax.swing.JTextField();
        jTextFieldDureePrevue = new javax.swing.JTextField();
        jButtonAnnuler = new javax.swing.JButton();
        jLabelTitrePrincipal = new javax.swing.JLabel();
        jButtonAjouter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelNumEtape.setText("Numero de L'etape :");

        jLabelDescription.setText("Description : ");

        jLabelDureePrevue.setText("Durée prevue :");

        jTextFieldNumEtape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumEtapeActionPerformed(evt);
            }
        });

        jTextFieldDureePrevue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDureePrevueActionPerformed(evt);
            }
        });

        jButtonAnnuler.setBackground(new java.awt.Color(255, 102, 102));
        jButtonAnnuler.setText("Annuler");
        jButtonAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnnulerActionPerformed(evt);
            }
        });

        jLabelTitrePrincipal.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTitrePrincipal.setText("Ajouter une etape");

        jButtonAjouter.setBackground(new java.awt.Color(153, 153, 255));
        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNumEtape, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelDureePrevue, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNumEtape, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDureePrevue, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabelTitrePrincipal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButtonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabelTitrePrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumEtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNumEtape))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDescription)
                    .addComponent(jTextFieldDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDureePrevue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDureePrevue))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAnnuler, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNumEtapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumEtapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumEtapeActionPerformed

    private void jButtonAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnnulerActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonAnnulerActionPerformed

    private void jTextFieldDureePrevueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDureePrevueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDureePrevueActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        // Récupère le contenu des cahmps de textes
    String NumEtape = jTextFieldNumEtape.getText(); 
    String Description = jTextFieldDescription.getText();
    String DureePrevue = jTextFieldDureePrevue.getText();
    
    // Vérifie si l'un des champs de texte est vide
    if (NumEtape.isEmpty() || Description.isEmpty() || DureePrevue.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Tous les champs doivent être remplis.");
        return; // Sortie de la méthode si des champs sont vides
    } 

    try {
        // Conversion des chaînes de caractères en types numériques
        int NumEtapeInt = Integer.parseInt(NumEtape);
        int DureePrevueInt = Integer.parseInt(DureePrevue);
        
        // Récupération du code d'excursion à partir de l'objet MiniExcursion
        String codeExcursion = excursionCourante.getCode(); // Utilise la variable d'instance

        // Insertion des données dans la base de données
        insertEtapeIntoDatabase(codeExcursion, NumEtapeInt, Description, DureePrevueInt);

        // Recharge la liste des excursions après l'ajout
        ((JFrameLesExcursions) getParent()).rechargerExcursions();
        this.dispose(); // Ferme la fenêtre actuelle
        
        // Vérifie que le nombre d'étape et la durée sont valides
        if (DureePrevueInt <= 0 || NumEtapeInt < 0) {
            JOptionPane.showMessageDialog(null, "Le nombre d'étape et la durée doivent être positifs.");
            return; // Sortie de la méthode si les valeurs ne sont pas valides
        }
    } catch (NumberFormatException e) {
        // Gestion des exceptions pour les conversions de type
        JOptionPane.showMessageDialog(null, "Veuillez entrer des valeurs numériques valides.");
        return; // Sortie de la méthode en cas d'erreur de format
    } catch (SQLException ex) {
        Logger.getLogger(JDialogaAjouterEtape.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    this.dispose(); // Ferme la fenêtre
    }//GEN-LAST:event_jButtonAjouterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogaAjouterEtape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogaAjouterEtape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogaAjouterEtape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogaAjouterEtape.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogaAjouterEtape dialog = new JDialogaAjouterEtape(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JButton jButtonAnnuler;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelDureePrevue;
    private javax.swing.JLabel jLabelNumEtape;
    private javax.swing.JLabel jLabelTitrePrincipal;
    private javax.swing.JTextField jTextFieldDescription;
    private javax.swing.JTextField jTextFieldDureePrevue;
    private javax.swing.JTextField jTextFieldNumEtape;
    // End of variables declaration//GEN-END:variables

}